Requires libboost-python

g++ -shared -fPIC maxflow.cpp graph.cpp wrapper.cpp -I/usr/include/python2.7 -lboost_python -lpython2.7 -omaxflow.so

Or, using cmake and the CMakeList.txt in this directory:

mkdir build
cd build
cmake ../.
make


